#!/bin/bash
#SBATCH --account=sheilman_1675
#SBATCH --partition=main
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --time=8:00:00
#SBATCH --ntasks=1
#SBATCH --mem=32G

echo "Postprocessing trees for dominating set problems"

cd /scratch1/alinadu/dominating_sets_patternboost/

module load conda
conda init
source ~/.bashrc
conda activate jl
JL_PYTHON=~/.conda/envs/jl/bin/python

TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

$JL_PYTHON find_positive_graph.py \
-e /scratch1/alinadu/dominating_sets_patternboost/test_run_2 \
-o /scratch1/alinadu/dominating_sets_patternboost/results_${TIMESTAMP}

TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

$JL_PYTHON find_positive_graph.py \
-e /scratch1/alinadu/dominating_sets_patternboost/test_run_2 \
-o /scratch1/alinadu/dominating_sets_patternboost/results_${TIMESTAMP} \
--layout planar