#!/bin/bash
#SBATCH --account=sheilman_1675
#SBATCH --partition=gpu
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --gpus-per-task=v100:1
#SBATCH --time=8:00:00
#SBATCH --ntasks=1
#SBATCH --mem=64G
#SBATCH --array=0-20

TREE_SIZES=(30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50)
N=${TREE_SIZES[$SLURM_ARRAY_TASK_ID]}

echo "Running with Prufer length N=$N"

cd /scratch1/alinadu/dominating_sets_patternboost/PatternBoost

module load conda
conda init
source ~/.bashrc
conda activate jl
JL_PYTHON=~/.conda/envs/jl/bin/python

$JL_PYTHON fc_loop.py --max_epochs 50000 \
--sample-only 100000 --max-steps 8000 \
--n_tokens 60 --dump_path experiment_output \
--exp_name tree_$N --nb_threads 64 \
--nb_local_searches 64000 --nb_nodes $N
